######################## default configuration ####################
baseURL = "/"
# relativeURLs = true

title = "ITG"
# theme = "slots-nj-hugo"
# post pagination
paginate = "8"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "itg" # get your shortname form here : https://disqus.com
# disable language
defaultContentLanguage = "ru"
disableLanguages = ["en", "ua"] # desable language from here
languageCode = "ru"


[outputs]
home = ["HTML", "RSS", "JSON"]
[outputFormats.RSS]
    mediaType = "application/rss+xml"
    baseName = "feed"

[permalinks]
  news = ':section/post-:year-:month-:day-:15:04/'
  top-news = ':section/post-:year-:month-:day-:15:04/'
  beginners = ':section/post-:year-:month-:day-:15:04/'
  articles = ':section/post-:year-:month-:day-:15:04/'

  
############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/match-height/jquery.matchHeight-min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific.popup.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"

############################## navigation ###############################
# main menu
[[menu.main]]
URL = "/"
name = "ГЛАВНАЯ"
weight = 1

[[menu.main]]
URL = "/news"
name = "НОВОСТИ"
weight = 2


[[menu.main]]
URL = "/articles"
name = "СТАТЬИ"
weight = 3


[[menu.main]]
URL = "/beginners"
name = "НОВИЧКАМ"
weight = 4


[[menu.main]]
URL = "#"
name = "КОМЬЮНИТИ"
weight = 5


[[menu.main]]
URL = "#"
name = "RESEARCH"
weight = 6


[[menu.main]]
URL = "#"
name = "ABOUT"
weight = 7
hasChildren = true





# footer menu
[[menu.footer]]
URL = "/news"
name = "Новости"
weight = 1

[[menu.footer]]
URL = "#"
name = "Геополитика"
weight = 2


[[menu.footer]]
URL = "#"
name = "Сводки"
weight = 3

[[menu.footer]]
URL = "#"
name = "Разместить статью"
weight = 4


[[menu.footer]]
URL = "#"
name = "Контакты"
weight = 5

#################### default parameters ################################
[params]
tagsLimit = 15
logo = "images/logo_w.svg"
logo_dark = "images/logo.svg"
logo_w = "98"
home = "Home"
# Meta data
description = "This is meta description"
author = "Anastasiia Berest"
# contact info

# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "get a quote"
link = "contact"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"



############################# social icon #################################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "#"


####
[[params.soc]]
icon = "images/icon/im.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/itg_official__/"

[[params.soc]]
icon = "images/icon/ytb.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UC4Blz7CAtrKwTL8mYt6LpfA"

[[params.soc]]
icon = "images/icon/tm.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://t.me/ITG_club"

[[params.soc]]
icon = "images/icon/tn.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://ru.tradingview.com/u/ITG_company"

[[params.soc]]
icon = "images/icon/tk.svg" # themify icon pack : https://themify.me/themify-icons
link = "http://www.tiktok.com/@itg_general__"

[[params.soc]]
icon = "images/icon/tw.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/ITG_General_"

[[params.soc]]
icon = "images/icon/fb.svg" # themify icon pack : https://themify.me/themify-icons
link = "https://www.facebook.com/InternationalTradeGroup2018"

[[params.soc]]
icon = "images/icon/email.svg" # themify icon pack : https://themify.me/themify-icons
link = "mailto: office@itg-investments.com"
################################### English language #####################################
[Languages.en]
contentDir = "content/en/"
home = "Home"
languageCode = "en-us"
languageName = "En"
weight = 2
[Languages.ru]
contentDir = "content/ru/"
home = "Главная"
languageCode = "ru"
languageName = "Ру"
weight = 1
[Languages.ua]
contentDir = "content/ua/"
home = "Головна"
languageCode = "ua"
languageName = "Укр"
weight = 3