backend:
  name: git-gateway
  branch: master

# local_backend:
#   url: "http://localhost:8076/api/v1"

media_folder: "/static/images"
public_folder: "/images"

# publish_mode: editorial_workflow

logo_url: "/images/favicon.png"
show_preview_links: false 

i18n:
  structure: multiple_folders
  locales: [ru, ua, en]
  default_locale: "ru"


collections:
  - label: 'Authors'
    name: 'authors'
    widget: "object"
    folder: 'content/authors'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: 'author-{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: 'author'
    editor:
      preview: false
    sortable_fields: ['date', 'author']
    fields:
      - { name: 'author', label: 'Author Name', widget: string, i18n: true }
  - label: 'Categories'
    name: 'categories'
    widget: "object"
    folder: 'content/categories'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: 'category-{{year}}-{{month}}-{{day}}-{{slug}}'
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['date', 'category']
    fields:
      - { name: 'category', label: 'category', widget: string, i18n: true }

  - label: "Аналитика"
    name: "analytics"
    folder: "content/"
    path: 'analytics/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "analytics-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["analytics"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/analytics", public_folder: "/images/analytics", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "Новости"
    name: "news"
    folder: "content/"
    path: 'news/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "news-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["news"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime",  date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/news", public_folder: "/images/news", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "Геополитика и финансы"
    name: "geopolitics"
    folder: "content/"
    path: 'geopolitics/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "geopolitics-and-finances-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["geopolitics"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/geopolitics", public_folder: "/images/geopolitics", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "БЛОКЧЕЙН"
    name: "blockchain"
    folder: "content/"
    path: 'blockchain/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "blockchain-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["blockchain"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/blockchain", public_folder: "/images/blockchain", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  
  - label: "КРИПТОВАЛЮТЫ"
    name: "crypto"
    folder: "content/"
    path: 'crypto/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "cryptocurrencies-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["crypto"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/crypto", public_folder: "/images/crypto", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "ЭКОНОМИКА"
    name: "economy"
    folder: "content/"
    path: 'economy/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "economy-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["economy"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/economy", public_folder: "/images/economy", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }

  - label: "МАЙНИНГ"
    name: "mining"
    folder: "content/"
    path: 'mining/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "mining-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["mining"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/mining", public_folder: "/images/mining", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
   
  - label: "ИНВЕСТИЦИИ"
    name: "investments"
    folder: "content/"
    path: 'investments/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "investments-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["investments"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/investments", public_folder: "/images/investments", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  
  - label: "ФИНАНСЫ"
    name: "finances"
    folder: "content/"
    path: 'finances/{{slug}}'
    format: 'frontmatter'
    create: true
    i18n: true
    slug: "finances-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    identifier_field: 'category'
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", name: "type", widget: "select",  options: ["finances"], required: true, i18n: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/finances", public_folder: "/images/finances", choose_url: true, required: false, i18n: true }
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
 
  - label: "YouTube"
    name: "youtube"
    folder: "content/"
    path: 'youtube/{{slug}}'
    slug: "youtube-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
    preview_path: "youtube/{{slug}}"
    create: true
    i18n: true
    editor:
      preview: false
    sortable_fields: ['']
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Type
        field: type
      - label: Drafts
        field: draft
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Type", i18n: true,  name: "type",  widget: "select",  options: ["youtube"], required: true }
      - { label: "Share", name: "share", widget: "boolean", i18n: true }
      - { label: "Date", name: "date", widget: "datetime",  date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, i18n: true }
      - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
      - { label: "Video URL", name: "video", widget: "string", i18n: true}
      - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/youtube", public_folder: "/images/youtube", choose_url: true, required: false, i18n: true}
      - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
      - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
      - { label: "Body", name: "body", widget: "markdown", required: false,  i18n: true }
    
  # - label: "Posts"
  #   name: "posts"
  #   folder: "content/"
  #   # path: 'top-news/{{slug}}'
  #   format: 'frontmatter'
  #   create: true
  #   i18n: true
  #   slug: "post-{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}"
  #   identifier_field: 'category'
  #   editor:
  #     preview: false
  #   sortable_fields: ['date', 'author', 'type']
  #   view_groups:
  #     - label: Year
  #       field: date
  #       pattern: \d{4}
  #     - label: Type
  #       field: type
  #     - label: Drafts
  #       field: draft
  #   fields:
  #     - { label: "Title", name: "title", widget: "string", i18n: true }
  #     - { label: "Type", name: "type", widget: "select",  options: ["top-news", "news", "articles", "beginners", "youtube"], required: true, i18n: true }
  #     - { label: "Position", name: "position",  widget: "select",  options: ["top-news-1", "top-news-2", "beginners-top", "news-1", "news-2", "news-3", "news-4", "none"], required: false, i18n: true }
  #     - { label: "Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: 'YYYY-MM-DDTHH:mm:ssZ', picker_utc: false, required: false, i18n: true }
  #     - { label: 'Authors', name: 'author', widget: 'relation', collection: 'authors', search_fields: ['author'], value_field: 'author', multiple: false, required: false, i18n: true }
  #     - { label: "Video URL", name: "video", widget: "string", required: false, i18n: true}
  #     - { label: "Img", name: "img", widget: "image", media_folder: "/static/images/top-news", choose_url: true, required: false, i18n: true }
  #     - { label: "Tags", name: "tags", widget: "list", allow_add: true, i18n: true }
  #     - { label: 'Categories', name: 'cat', widget: 'relation', collection: 'categories', search_fields: ['categoty'], value_field: 'category', multiple: false, required: false, i18n: true }
  #     - { label: "Body", name: "body", widget: "markdown", i18n: true }
